### ISSUE TITLE
Potential mismatch between Integration Configuration documentation names and example.

### ISSUE THREAD

**Issue by PedroD** [Talkdesk/api#13]
Hello,

As I was reading the documentation concerning the [Integration Configuration JSON structure](https://github.com/Talkdesk/api/tree/master/integrations/configuration#integration-configuration), I've noticed that the field whose name is referred to as **authentication_fields** may actually relate to the field **authentication_configuration** in the example configuration JSON from the same section.

	{
	  "name": "zendesk",
	  (...)
	  "authentication_configuration": [  <------- Should this be named "authentication_fields" instead?
		{
		  "account": { "source": "input", "display": "Account", "mandatory": true, "type": "input", "store": true, "format": "https://{{account}}.zendesk.com" }
		},
		(...)
	  ],
	  "auth_validation_endpoint": "https://td-zendesk.herokuapp.com/auth_validation",
	  (...)
	}

Am I misinterpreting the documentation somehow?

**Comment by axfcampos** [comment]
Thanks for pointing that out, they do refer to the same field. Mismatching name :+1:

Apologies for the confusion as this document hasn't been update in a while :smile:

**Comment by PedroD** [comment]
No problem, thanks! :)
